### ISSUE TITLE
Invalid multibyte string using R 3.6.0

### ISSUE THREAD

**Issue by michstrauch** [chrisschuerz/SWATplusR#1]
Using R version 3.6.0, I get the following error message when running the FAST sensitivity analysis for a SWAT2012 project (code below): 

Error in substr(., 1, 16) : invalid multibyte string, element 20

Using R 3.5.2, however, works. Just to let you know that there is a problem with the newest version ;)

R code:

par_names <- c("GW_DELAY.gw | change = absval",
               "OV_N.hru | change = absval",
               "CN2.mgt | change = relchg",
               "SOL_AWC.sol | change = relchg",
               "SURLAG.bsn | change = absval",
               "ESCO.hru | change = absval",
               "GWQMN.gw | change = absval",
               "ALPHA_BF.gw | change = absval",
               "LAT_TIME.hru | change = absval",
               "SLSOIL.hru | change = absval",
               "HRU_SLP.hru | change = absval",
               "CH_K2.rte | change = absval",
               "SOL_Z.sol | change = relchg",
               "CH_K1.sub | change = absval",
               "SLSUBBSN.hru | change = absval",
               "CANMX.hru | change = absval",
               "CH_N2.rte | change = absval",
               "CH_N1.sub | change = absval",
               "EVRCH.bsn | change = absval",
               "GW_REVAP.gw | change = absval",
               "RCHRG_DP.gw | change = absval",
               "EPCO.hru | change = absval")

par_fast <- fast_parameters(
  minimum = c(30, 0.01, -0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.2, 0, 10, 0, 0, 0.01, 0.5, 0, 0, 0),
  maximum = c(450, 30, 0.2, 0.2, 24, 1, 5000, 1, 180, 150, 0.6, 500, 0.2, 300, 150, 100, 0.3, 30, 1, 0.3, 1, 1),
  names = par_names) %>%
  as_tibble()

q_fast <- run_swat2012(project_path = path,
                       output = define_output(file = "rch",
                                              variable = "FLOW_OUT",
                                              unit = 4),
                       parameter = par_fast,
                       start_date = "2004-01-01",
                       end_date = "2009-12-31",
                       years_skip = 1,
                       n_thread = 20)

**Comment by chrisschuerz** [comment]
I was able to reproduce the error. It seemed to be a problem with special characters in the function `substr()` that now occurs with R3.6.0, but was not present in older R versions. I fixed the problem by replacing `substr()` with `stringr::str_sub()` that does not show this issue. I updated some other small issues together with that. That issue should be solved now in SWATplusR 0.2.6.9000. I fixed this in the master branch and not in the dev branch, as this seems to be an urgent issue. Therefore for the moment a development revision on the master branch.
