### ISSUE TITLE
Monthly output_interval in run_swat2012

### ISSUE THREAD

**Issue by josevalles7** [chrisschuerz/SWATplusR#10]
Hi there, 

I´ve been exploring your SWATPlusR and have encounter a problem in demo version that i am running. 

When I run the following code: 
`q_sim_2012 <- run_swat2012(project_path = path_2012, output = define_output(file = "rch", variable = "FLOW_OUT", unit = 1:3), output_interval = "m", years_skip = 1)`

it provides the following error: 

Building 1 thread in './Documents/R/swat2012_rev622_demo/.model_run': 
 Completed 1 thread in 1S                                                   
Performing 1 simulation on 1 cores: 
 Completed 1 simulation in 3S                                               
Error: Argument 2 must be length 144, not 145

However when I replace the output_interval to "d" o "y", the model runs perfectly. 

Any comments about this issue? 

thanks in advance for your reply

**Comment by chrisschuerz** [comment]
Hi Jose,

I remembered that one other SWATplusR user reported that issue some while ago (although via email) so it is not reported here. I should have fixed that issue already. I just tested your code on my computer and it actually worked. Could you tell me what version of SWATplusR and what SWAT2012 revision (if it is different to the one included in the demo  you were using? 

Cheers,
Christoph

**Comment by josevalles7** [comment]
Hi Christoph, 

Thank you for you reply. I am using the SWATplusR_0.2.7 version and the revision is not different from the one included in your demo, 

Could it be something related to the date format? 

let me know if you need more info. You can contact me via email if you would like

Regards

**Comment by chrisschuerz** [comment]
I fixed the issue with version 0.2.8.9002. So please update SWATplusR simply running the code to install again:

```
devtools::install_github("chrisschuerz/SWATplusR")
```
This should fix the issue. Please check the SWATplusR version afterwards. It should be 0.2.8.9004 now.

**Comment by josevalles7** [comment]
Thanks!! I really appreaciate it

I updated the SWATplusR to the newest version and it works perfectly.
