### ISSUE TITLE
modify one parameter several times in one run

### ISSUE THREAD

**Issue by Svenja-vS** [chrisschuerz/SWATplusR#11]
Hello,

At the moment I am facing the problem that I want to change on parameter (CN2) that I want to modify depending on the regional land use.
See example below:

`par_mod <- tibble ("CN2.mgt|change = absval| luse %in% 'PINH'" = 60,
                                "CN2.mgt|change = absval| luse %in% 'EUCO'" = 55)` 

I got the following error message:
`Error in translate_parameter_constraints(names(parameter)) : 
  Duplicated parameter names found! Define individual names with:
par_name::parameter|..`

I am not quite sure how to solve the problem, any kind of ideas are welcome :)
Thanks in advance
Svenja

**Comment by chrisschuerz** [comment]
Hi,

for the function the two parameters do have the same name. Actually, they are two different parameters e.g. `cn2_pinh` and `cn2_euco`. Therefore you have to assign two unique names to them. Please see the [Getting started](https://chrisschuerz.github.io/SWATplusR/articles/SWATplusR.html#model-parameter-alteration) page of SWATplusR to see how to do that. A minimum example for that would be:

```
par_mod <- c("cn2_pinh::CN2.mgt|change = absval | luse %in% 'PINH'" = 60)
```

Cheers, 
Christoph

**Comment by Svenja-vS** [comment]
Hello,
thanks that works of course. 
Svenja
