### ISSUE TITLE
Problem during SWATplusR installation

### ISSUE THREAD

**Issue by NicoDallaLibera** [chrisschuerz/SWATplusR#12]
Dear  Christoph,

I'm trying to install your SWATplusR packages in R (R version 3.5.2 (2018-12-20) -- "Eggshell Igloo") but I keep facing the following errors/warnings.

Please let me know how to solve this problem.

Thanks so much.

Best regards

Nico

**> install.packages("devtools")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("devtools")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Windows7/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
provo con l'URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/devtools_2.2.2.zip'
Content type 'application/zip' length 347529 bytes (339 KB)
downloaded 339 KB

package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Windows7\AppData\Local\Temp\RtmpwTTCUQ\downloaded_packages
> devtools::install_github("chrisschuerz/SWATplusR")
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Errore: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Resolving timed out after 10000 milliseconds**

**Comment by chrisschuerz** [comment]
Hi Nico,

I am sorry that I did not respond earlier. This Error is odd. I am not sure if it is directly related to `SWATplusR`. Have you tested installing any other packages from GitHub with `devtools`? Did it work?

Cheers 
Christoph

**Comment by heomal** [comment]
Hi Nico,

You need to download and install  Rtools on your machine. After that, it should work.

Heou Maleki

**Comment by NicoDallaLibera** [comment]
Hi Christoph,
This is not the first time I install packages from github but it's the
first time I run into that kind of error. Could it be related to the newer
version of R? When I installed the other packages I was running a lower
version of R, for sure. At this time, I've not installed Rtool on my laptop
but I know that it's not neccessy unless to develop a new package, and this
is not the case.

Are there other ways to install it? I saw SWATplusR is not available under
the list of CRAN's available packages, thus I cannot install it directly
from R or RStudio as the other packages (i.e.: gstat or EnvStats).

Thanks for your help

Cheers

Ph.D. Geol. Nico Dalla Libera
(sent from mobile)

Il sab 11 apr 2020, 15:43 Christoph Schuerz <notifications@github.com> ha
scritto:

**Comment by MalekiB** [comment]
I may be wrong but having had the same issue, I could install SWATPlusR successfully after installing Rtools on my machine. On a virtual machine I am also using and which has the latest version of R and RStudio, SWATPlusR was installed without this error. 
I know Rtools is for package development but I also know that devtools has so many dependencies and for some oldr versions, it requires Rtools. It is a suggestion.

Heou M.

**Comment by NicoDallaLibera** [comment]
Dear Heou,
Thanks for your suggestion. I will try to follow it.

Cheers

Ph.D. Geol. Nico Dalla Libera
(sent from mobile)

Il dom 12 apr 2020, 12:50 MalekiB <notifications@github.com> ha scritto:

**Comment by chrisschuerz** [comment]
Hi Heou,

yes you might be right with Rtools. Testing the installation on Windows machines worked worked also without having Rtools. But it is worth trying, particularly as Nico gets the warning of not having Rtools instlalled.

Cheers Christoph

**Comment by NicoDallaLibera** [comment]
Hello Christoph,
I installed your SWATplusR package but I'm not able to complete your demo
for SWAT+. The cause is the following error:










*q_sim_plus <- run_swatplus(project_path =
path_plus,+                            output = define_output(file =
"channel",+                                                   variable =
"flo_out",+                                                   unit =
1))Building 1 thread in
'D:/Lavoro/R_learning/SWATplusR/Demo/swatplus_rev57_demo/.model_run':
 Completed 1 thread in 0S
Error in if (revision < 57) { : argument is of length zeroIn addition:
Warning messages:1: `tz` argument is ignored by `as_date()` 2: `tz`
argument is ignored by `as_date()` *

Since I'm following your GitHub tutorial and script I cannot understand the
reason why of it, especially the line "*Error in if (revision < 57) { :
argument is of length zero*".
I don't have revisions earlier than 57.

Could you explain me why this error appears and how to fix it?

Thanks so much.

Regards,
Nico


*---------------------------------------------------------------------------------------------------------------Geol.
**Nico Dalla Libera, PhD*

*E-mail: **nico.dallalibera@gmail.com <nico.dallalibera@gmail.com>*
*PEC: **nico.dallalibera@peceasy.com <nico.dallalibera@peceasy.com>*
*Skype account:** nicodalla2*

**Comment by chrisschuerz** [comment]
Hi Nico,

I implemented the if statement to ask for the revision number, because there are large differences between rev 57 and newer ones. This was necessary when many people still used rev 57, but might be more and more obsolete now.

I got already the feedback, that the routine in the code that should figure out the revision number causes issues from time to time. Dou you always encounter this problem or only sometimes?

Anyways, I plan to remove this routine when I find time for that. You will find that fix in the updated version of the R package. I hope I find time this or next week to fix that.

Cheers, 
Christoph

**Comment by NicoDallaLibera** [comment]
Hi Christoph,
I run always into that error when I use "run_swatplus" command. Clearly,
I'm using a newer revision of SWAT+ so "rev" command should be unnecessary.
If I did not set "rev" command the code should use the swat+ revision it
finds within the model path, doesn't it?

In addition, I have a question about the sensitivity analysis script. When
you perform FAST or Sobol analysis, why do you divide your simulated
discharge by 8.64? Is your observed discharge unit different from m3/s? You
never stated the observed discharge unit so I supposed your observations
are not in m3/s as simulated ones.

nse_fast <- q_fast$simulation$q_sim %>%
  select <https://dplyr.tidyverse.org/reference/select.html>(-date) %>%
  *map_dbl <https://purrr.tidyverse.org/reference/map.html>(., ~NSE
<https://www.rdocumentation.org/packages/hydroGOF/topics/NSE>(.x/8.64,
q_obs$**discharge)*) Thanks so much. Nico

*---------------------------------------------------------------------------------------------------------------Geol.
**Nico Dalla Libera, PhD*

*E-mail: **nico.dallalibera@gmail.com <nico.dallalibera@gmail.com>*
*PEC: **nico.dallalibera@peceasy.com <nico.dallalibera@peceasy.com>*
*Skype account:** nicodalla2*

**Comment by chrisschuerz** [comment]
Hi Nico,

unfortunately the user cannot access the rev variable it is set while running the model. But I will get rid of that in the update of the R package. But you could test to set rev to `rev <- 59.3` outside of the function. Maybe this could be a workaround as when the variable is not assigned internally in the function execution it might access the variable of the global environment.

The division by 8.64 should be also obsolete now. You see many things are unfortunately not up to date. But I did not find time yet to update them. The 8.64 were necessary to convert the units from ha*m to m^-3 s^-1. Up to revision 59.0 the discharges were given in ha*m. But Jeff realized now that the SWAT community did not like that and now both in ha*m and m^-3 s^-1 are provided. So always check what output you are using.

Christoph

**Comment by NicoDallaLibera** [comment]
Hi Christoph,
Many thanks for your reply. I will test your hint about rev command and I
will keep you posted.

Nico

*---------------------------------------------------------------------------------------------------------------Geol.
**Nico Dalla Libera, PhD*

*E-mail: **nico.dallalibera@gmail.com <nico.dallalibera@gmail.com>*
*PEC: **nico.dallalibera@peceasy.com <nico.dallalibera@peceasy.com>*
*Skype account:** nicodalla2*

**Comment by NicoDallaLibera** [comment]
Hi Christoph,
I'm here for asking you about an issue coming out during the sensitivity
analysis. I'm using your code available on GitHub page "02 - Sensitivity
analysis and model calibration".
When I run the global sensitivity code (FAST or SOBOL, it doesn't matter),
often, an R fatal error appears, saying " a fatal error occurs - R session
aborted" but I don't understand why. Sometimes the code runs well, others
it leads to R crash. Do you have any idea for that?
The same issue often jumps out for optimization code as well.

Thanks so much,
Hope you can give me some hints to fix it.

Cheers!

Nico

*---------------------------------------------------------------------------------------------------------------Geol.
**Nico Dalla Libera, PhD*

*E-mail: **nico.dallalibera@gmail.com <nico.dallalibera@gmail.com>*
*PEC: **nico.dallalibera@peceasy.com <nico.dallalibera@peceasy.com>*
*Skype account:** nicodalla2*

**Comment by chrisschuerz** [comment]
Hi Nico,

I did not run the code now for quite a while. But it should actually run. It is the first time that I hear from a user that the entire R session crashes because of running SWAT with SWATplusR.

So I am sorry that I do not have any immediate fixes for that issue.
All the best 
Christoph

**Comment by chrisschuerz** [comment]
Hi Nico,

is the issue still present or was it solved? To clean up the issue section of `SWATplusR` I suggest to close this issue. Please reopen it with an updated comment if issues still exist.

Cheers Chris
