### ISSUE TITLE
Issue with optimization

### ISSUE THREAD

**Issue by heomal** [chrisschuerz/SWATplusR#13]
Hi Christoph

After successully running a SWAT+ model, I have been testing the optimization but noticed that it always returns the initial values as optimal parameters wether I use BFG or SCE. The results of optimization only change when I change the initial values. It doesn't seem to search for optimal parameters within the specifies intervals.
Could you help on this?

Thanks in adavance.

Heou M.

**Comment by chrisschuerz** [comment]
Hi,

have you checked already if the parameter changes work effectively in your model setup? There is unfortunately the issue with SWAT+ that parameter calibration is not working if you set up the model with the SWAT Editor but did not perform any parameter changes with the Editor. To fix this you have to manually the "chg" line in the file.cio as Jaclyn and I have already posted here: https://groups.google.com/forum/#!topic/swatplus/PMcC_zKsQMg 

Please just check if that is the issue. You can test it with a small run in R where you assign two different values to cn2 for example. If that is not the issue I will think of other solutions.

Any ways the optimization is still a little error prone as the routine to identify the model revision number can cause errors and break the optimization run. I have also planned to fix this in the future, but did not find time yet.

**Comment by MalekiB** [comment]
Hi Christoph,

Thanks for your reply and suggestion.
I have checked and there was that problem in the file.co. I have changed the line as raised by Jaclyn but the problem still persists.
I will now try with SWAT instead of SWAT+ and see if this problem occurs. 
Thanks.

Heou

**Comment by chrisschuerz** [comment]
Is this still an issue that is related to `SWATplusR`? Otherwise I would close it to clean up the package's issue section.

**Comment by chrisschuerz** [comment]
If the issue still exists, please reopen the issue with an updated comment on the current status.

Cheers Chris
