### ISSUE TITLE
Running a modified version of a SWAT2012 project

### ISSUE THREAD

**Issue by rafaelnavas** [chrisschuerz/SWATplusR#14]
Hi Chris, I want to run a modified version of a SWAT2012 project with your package.

First, I modify & save the SWAT project as follows:

par_single1 <- c("cn2.hru|change = pctchg" = - 5,
                "alpha.gw|change = absval" = 0.5)

run_swat2012(project_path = "C:/swat2012_rev622_demo",
             output = define_output(file = "rch",
                                    variable = "FLOW_OUT",
                                    unit = 1),
            keep_folder = T,
             return_output = F,
            run_path = "C:/swat2012_rev622_demo/demo_run",
            parameter = par_single1)

At this step, the modified version of the demo is stored at run_path.

Second, I looking to modify the stored version of the model. But the names of the variables are not in the txt files of the new stored version of the model. 

par_single2 <- c("cn2.hru|change = pctchg" =  10,
                 "alpha.gw|change = absval" = 0.8)

run_swat2012(project_path = "C:/swat2012_rev622_demo/demo_run/.model_run/thread_1",
             output = define_output(file = "rch",
                                    variable = "FLOW_OUT",
                                    unit = 1),
             parameter = par_single2,
             return_output = F)
 
The error message is
Error: Columns `0`, `0`, `0`, `0`, `0`, ... must have a unique name

Thank you,

Rafael

**Comment by chrisschuerz** [comment]
Hi Rafael,

I think there are several thinks to clarify in your code:

- **Parameter definition**:
You defined CN2 and ALPHA for SWAT2012 as follows:
`par_single1 <- c("cn2.hru|change = pctchg" = - 5,
"alpha.gw|change = absval" = 0.5)`
The used names are however the parameter names in SWAT+.
The correct definition is as follows:
`par_single1 <- c("CN2.mgt|change = pctchg" = - 5,
"ALPHA_BF.gw|change = absval" = 0.5)`

- It is not fully clear to me why you want to modify a model and save it and then run the new model again to modify the same parameter, but never write outputs.

- The error message surprises me as you basically do the same thing twice, where no error occurs the first time.

Maybe try to run it first with the correct parameter names and check if it works? We should come back to the other issue afterwards.

Cheers Christoph

**Comment by rafaelnavas** [comment]
Hi Chris,
Answering your question. Basically I have 3 things in my mind:

1. Sequential Calibration: e.g. Calibrate first upstream, then downstream adding some constraints. Of course, we can do that with the parameters obtained from the 1st calibration. However, could be more simple if we can save the optimized version of the model on the 1st optimization trial.   

2. Sharing the model: In some cases could be convenient to share directly the optimized version of the model without a parameters file. That simplifies the analysis, especially for those people that are not familiarized with R. In other words, to let other people reproduce my results, I have to give the optimized parameters. So, I'm looking to simplify a little. 

3. Running out of R: How can we run the optimized version of the SWAT model out of the R environment?  Maybe you have some kind of "export" function that I don't know.    

Please forget all this, if my query implies a huge effort from your part.

About your comment "The error message surprises me as you basically do the same thing twice, where no error occurs the first time" Sorry, I made a mistake. The right code is as follow:


> # 1st change (change CN2 and save the new version of the model, the code produces a new version of the model which is stored in run_path)
> 
> par_single1 <- c("CN2.mgt|change = pctchg" = - 5)
> 
> run_swat2012(project_path = "C:/swat2012_rev622_demo",
+               keep_folder = TRUE,
+              run_path="C:/new_demo",
+              parameter = par_single1,
+              output = define_output(file = "rch",
+                                     variable = "FLOW_OUT",
+                                     unit = 1),
+              return_output=FALSE)
Building 1 thread in 'C:/new_demo/.model_run': 
 Completed 1 thread in 3S                                                   
Performing 1 simulation on 1 cores: 
 Completed 1 simulation in 6S  


#######################################################################
> # 2nd change (modify the new version of the model, e.g. Curve number) 
> 
> par_single2 <- c("CN2.mgt|change = pctchg" = - 15)
> 
> run_swat2012(project_path = "C:/new_demo/.model_run/thread_1",
+              parameter = par_single1,
+              output = define_output(file = "rch",
+                                     variable = "FLOW_OUT",
+                                     unit = 1),
+              return_output=FALSE)
Error: Columns `0`, `0`, `0`, `0`, `0`, ... must have a unique name


######################################################################
> # 2nd change (modify the new version of the model, other example with alpha.gw, same error) 
> 
> par_single2 <- c("alpha.gw|change = absval" = 0.8)
> 
> run_swat2012(project_path = "C:/new_demo/.model_run/thread_1",
+              parameter = par_single1,
+              output = define_output(file = "rch",
+                                     variable = "FLOW_OUT",
+                                     unit = 1),
+              return_output=FALSE)
Error: Columns `0`, `0`, `0`, `0`, `0`, ... must have a unique name

Thank you,
Rafael

**Comment by chrisschuerz** [comment]
Hi Rafael,

I am really sorry to come back so late to your issues. Last weeks were a bit chaotic. 

to your points above:

1. Yes this makes sense to me (although I am not a big fan of sequential calibration). This you could solve in different ways. Either you do your upstream calibration and keep the "best" parameter set for the upstream subbasins and simply add the selected parameters as static values in your next parameter set, or you do as you suggested and run the model with your selected parameter set and use that model for your next round of calibration. Be careful here with only modifying the parameters in the right subbasins and that you do not overwrite you parameter values from the previous iteration.

```r
# Example of keeping parameters in set:
par_iter2 <- c("cn_upstream::CN2.mgt|change = abschg | sub == 1:3" = 1.23456,
               "cn_downstream::CN2.mgt|change = abschg | sub == 4:10" = runif(100,-25,25)
``` 

2. Also that is a good point. Especially when you want to share your model with non R users. For that I planned already to write a function that only rewrites the parameter values and does not run the model. But I just do not find the time for that right now.

3. This point is a combination of points 1. and 2. I think bot options would work. Either you provide the "best" parameter set as a variable in R or you write the parameters into the SWAT files and provide that model.

The error you generated is really interesting. I will try to reproduce it when I get back to my Windows computer. I will come back to you when I was able to reproduce and/or fix it.

Sorry again for my late reply.

Cheers Chris

**Comment by chrisschuerz** [comment]
I am closing this as I am not sure if the discussion is still relevant @rafaelnavas please reopen the issue if it needs further discussion.
