### ISSUE TITLE
Error in if (revision < 57)

### ISSUE THREAD

**Issue by AndresSaracho** [chrisschuerz/SWATplusR#15]
Does my regional configuration is causing this problem?

> q = run_swatplus(project_path = "E:/demo/swatplus_rev57_demo", 
+                  output = define_output(file = "channel",
+                                         variable = "flo_out",
+                                         unit = 1))
Building 1 thread in 'E:/demo/swatplus_rev57_demo/.model_run': 
 Completed 1 thread in 1S                                                   
Error in if (revision < 57) { : argumento tiene longitud cero
Además: Warning messages:
1: `tz` argument is ignored by `as_date()` 
2: `tz` argument is ignored by `as_date()` 

> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Uruguay.1252  LC_CTYPE=Spanish_Uruguay.1252    LC_MONETARY=Spanish_Uruguay.1252 LC_NUMERIC=C                    
[5] LC_TIME=Spanish_Uruguay.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SWATplusR_0.2.8.9004

loaded via a namespace (and not attached):
 [1] tidyselect_1.0.0  xfun_0.13         remotes_2.1.1     purrr_0.3.4       vctrs_0.2.4       generics_0.0.2    doSNOW_1.0.18    
 [8] testthat_2.3.2    htmltools_0.4.0   usethis_1.6.0     snow_0.4-3        yaml_2.2.1        blob_1.2.1        rlang_0.4.5      
[15] pkgbuild_1.0.7    pillar_1.4.3      glue_1.4.0        withr_2.2.0       DBI_1.1.0         bit64_0.9-7       dbplyr_1.4.3     
[22] sessioninfo_1.1.1 foreach_1.5.0     lifecycle_0.2.0   stringr_1.4.0     devtools_2.3.0    evaluate_0.14     codetools_0.2-16 
[29] memoise_1.1.0     knitr_1.28        callr_3.4.3       ps_1.3.2          parallel_3.6.3    curl_4.3          fansi_0.4.1      
[36] Rcpp_1.0.3        readr_1.3.1       backports_1.1.6   desc_1.2.0        pkgload_1.0.2     fs_1.4.1          bit_1.1-15.2     
[43] hms_0.5.3         digest_0.6.25     stringi_1.4.6     processx_3.4.2    dplyr_0.8.5       rprojroot_1.3-2   cli_2.0.2        
[50] tools_3.6.3       magrittr_1.5      tibble_3.0.1      RSQLite_2.2.0     crayon_1.3.4      pkgconfig_2.0.3   ellipsis_0.3.0   
[57] prettyunits_1.1.1 lubridate_1.7.8   rmarkdown_2.1     assertthat_0.2.1  rstudioapi_0.11   iterators_1.0.12  R6_2.4.1         
[64] compiler_3.6.3

**Comment by chrisschuerz** [comment]
Hi Andres,

I am not so sure if the locale causes the issue (I think it only results in warnings that do not have an impact). The error itself is caused by checking which revision number of SWAT+ you are using. From other comments I found that this check behaves different on different computers. So it was always difficult for me to verify that. But this is definitely something that I will fix in an update. I am sorry that I cannot immediately fix this issue. But I will handle that soon.

Cheers Christoph

**Comment by huangguacui** [comment]
Hi,

I also got similar error. Hope you can consider it in an update fix @chrisschuerz . Thanks.

Building 1 thread in 'D:/demo/swatplus_rev57_demo/.model_run': 
 Completed 1 thread in 0S                                                   
Error in system(run_batch, intern = TRUE, timeout = 1) : 'D:/R' not found
In addition: Warning messages:
1: `tz` argument is ignored by `as_date()` 
2: `tz` argument is ignored by `as_date()` 

R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252

**Comment by chrisschuerz** [comment]
Thank you for the feedback! I am really surprised that so many R users now find that issue permanently. I will fix it as soon as possible.

Cheers,
Christoph

**Comment by WillemVervoort** [comment]
> Hi,
> I also got similar error as huangguacui.
> 
> Building 1 thread in 'C:/Rubina/R FILES/SWATplusR/swatplus_rev57_demo/.model_run':
> Completed 1 thread in 0S
> Error in system(run_batch, intern = TRUE, timeout = 1) :
> 'C:/Rubina/R' not found
> In addition: Warning messages:
> 1: `tz` argument is ignored by `as_date()`
> 2: `tz` argument is ignored by `as_date()`
> 
> Kindly let me know how to fix it. Thanks

This error and the one before is simply in your path. SWATplusR does not seem to like "spaces" in your path name, Try defining project_path that has not "spaces" in the path name.

The tz argument is only a warning, but suggest that there might be something wrong with the translation of dates. This could be problematic, but I am unclear how this would relate to the revision error.

**Comment by WillemVervoort** [comment]
> Does my regional configuration is causing this problem?
> 
> > q = run_swatplus(project_path = "E:/demo/swatplus_rev57_demo",
> 
> * ```
>                output = define_output(file = "channel",
>   ```
> * ```
>                                       variable = "flo_out",
>   ```
> * ```
>                                       unit = 1))
>   ```
> 
> Building 1 thread in 'E:/demo/swatplus_rev57_demo/.model_run':
> Completed 1 thread in 1S
> Error in if (revision < 57) { : argumento tiene longitud cero
> Además: Warning messages:
> 1: `tz` argument is ignored by `as_date()`
> 2: `tz` argument is ignored by `as_date()`
> 
> > sessionInfo()
> > R version 3.6.3 (2020-02-29)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Spanish_Uruguay.1252 LC_CTYPE=Spanish_Uruguay.1252 LC_MONETARY=Spanish_Uruguay.1252 LC_NUMERIC=C
> [5] LC_TIME=Spanish_Uruguay.1252
> 
> attached base packages:
> [1] stats graphics grDevices utils datasets methods base
> 
> other attached packages:
> [1] SWATplusR_0.2.8.9004
> 
> loaded via a namespace (and not attached):
> [1] tidyselect_1.0.0 xfun_0.13 remotes_2.1.1 purrr_0.3.4 vctrs_0.2.4 generics_0.0.2 doSNOW_1.0.18
> [8] testthat_2.3.2 htmltools_0.4.0 usethis_1.6.0 snow_0.4-3 yaml_2.2.1 blob_1.2.1 rlang_0.4.5
> [15] pkgbuild_1.0.7 pillar_1.4.3 glue_1.4.0 withr_2.2.0 DBI_1.1.0 bit64_0.9-7 dbplyr_1.4.3
> [22] sessioninfo_1.1.1 foreach_1.5.0 lifecycle_0.2.0 stringr_1.4.0 devtools_2.3.0 evaluate_0.14 codetools_0.2-16
> [29] memoise_1.1.0 knitr_1.28 callr_3.4.3 ps_1.3.2 parallel_3.6.3 curl_4.3 fansi_0.4.1
> [36] Rcpp_1.0.3 readr_1.3.1 backports_1.1.6 desc_1.2.0 pkgload_1.0.2 fs_1.4.1 bit_1.1-15.2
> [43] hms_0.5.3 digest_0.6.25 stringi_1.4.6 processx_3.4.2 dplyr_0.8.5 rprojroot_1.3-2 cli_2.0.2
> [50] tools_3.6.3 magrittr_1.5 tibble_3.0.1 RSQLite_2.2.0 crayon_1.3.4 pkgconfig_2.0.3 ellipsis_0.3.0
> [57] prettyunits_1.1.1 lubridate_1.7.8 rmarkdown_2.1 assertthat_0.2.1 rstudioapi_0.11 iterators_1.0.12 R6_2.4.1
> [64] compiler_3.6.3

I am getting exactly the same revision error and the tz warning. I have been digging in the code and when I run things line-by-line I can't reproduce the error, however when I run run_swat_plus() it fails. 

The error seems to be generated within translate_outfile_names(). However, again, I cannot reproduce the error if I run this function separately (after defining the inputs required).

I assume the tz warning is generated in the section of swatplus_setup_runfiles() where you generate the start and finish dates. I can look at that in a bit more detail. I am stumped about the revision atm. I will setup a testing branch in my fork and add a PR if I can fix it.

**Comment by WillemVervoort** [comment]
@chrisschuerz Chris,
I have found a solution and adjusted the code. I will create a PR tomorrow night for you to approve. It took me quite a while to dig it out.
The error occurs because you have a 1 sec timeout on the batch file run and you need more time on some machines. I have increased it to 3 sec and that solved the problem
If in a later version you remove the version test it should dissappear
