### ISSUE TITLE
Error in calibration

### ISSUE THREAD

**Issue by Jakirullah** [chrisschuerz/SWATplusR#16]
Dear Christoph

I am getting this error message while I am calibrating my newly developed model with SWAT2012. I have noticed all output files are empty. 

-----------------------------------------------------------------------------------------------------------
Image#01
![image](https://user-images.githubusercontent.com/18727309/81682029-e2b68e80-9454-11ea-83c4-b8c82118f874.png)
-------------------------------------------------------------------------------------------------------------
Image#02
![image](https://user-images.githubusercontent.com/18727309/81682595-34f7af80-9455-11ea-83cf-b7583f14b755.png)

Do you have any idea why it is not working or what I am missing here?

Best regards
Jakir

**Comment by chrisschuerz** [comment]
From what you provided I cannot see any issues. Have you checked that the number of years you simulate is longer than the number of years you skip before writing outputs?

Cheers,
Christoph
