### ISSUE TITLE
requirement of reading output.rch

### ISSUE THREAD

**Issue by earthcli** [chrisschuerz/SWATplusR#2]
It is seems a great package.
While I am searching a package for speeding reading output.rch now.
How can I use this package to achieve this? I mean I have done the simulation and resulted in a 1.2G big file of output.rch at daily scale, it takes 2 hours to read and wrap the file. I want to speed it with your package, how should I do? 
Thanks.

**Comment by chrisschuerz** [comment]
I am not sure if SWATplusR provides a direct solution to your problem, as it only reads the outputs AFTER executing the SWAT model. Concerning reading out the output files I did not benchmark the routines with such large output files (at least for SWAT2012). In SWATplusR I use `readr::read_fwf` to read fixed width format tables. It seems to be quite efficient. Though you could also have a look into the data.table package.

**Comment by chrisschuerz** [comment]
I am cleaning up the issues page. As this is not really under discussion anymore I would close this issue.
