### ISSUE TITLE
Error running a modified version of SWATplus

### ISSUE THREAD

**Issue by florentpapini** [chrisschuerz/SWATplusR#22]
Hi Christoph,

I am currently developping a modified version of SWATplus with new water routing routines, so I have to use a modified SWATplus.exe file on SWATplusR. 

It was working well until recently on both SWATplusR and my Visual Studio project. I did a lot of modifications inside SWATplus and it's still working on my Visual Studio project but not anymore on SWATplusR. Even double clicking on the .exe in TxtInOut works.

Tell me if you need more details on my modified SWATplus.

Thanks, 
Florent

Here is the error while running run_swatplus function: 
Error in { : task 1 failed - "Zero-length begin and end specifications not supported"
4. stop(simpleError(msg, call = expr))
3. e$fun(obj, substitute(ex), parent.frame(), e$data)
2. foreach(i_run = 1:n_run, .packages = c("dplyr", "lubridate"), .options.snow = opts) %dopar% { worker_id <- paste(Sys.info()[["nodename"]], Sys.getpid(), sep = "-") ...
1. run_swatplus(project_path = project_path, run_path = project_path, output = define_output(file = "channel_sd", variable = "flo_out", unit = 2), start_date = "2007-3-1", end_date = "2015-8-25", years_skip = 2)

**Comment by chrisschuerz** [comment]
Hi Florent,

I think we discussed this issue then via email? To clean up the issues section I would close this issue then. If you want to continue to discuss this issue (if it is  related to `SWATplusR`) I would ask you to reopen this issue with an updated issue description.

Cheers Chris
