### ISSUE TITLE
Unable to install SwatplusR

### ISSUE THREAD

**Issue by Ansh2506** [chrisschuerz/SWATplusR#27]
Hi Chris, 

So i tried to install the package, but before that I tried installing the devtools package. 

When I run this line of code  devtools::install_github("chrisschuerz/SWATplusR")

I get the following error:
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’

Are you please able to assist me?

Ansh

**Comment by WillemVervoort** [comment]
Try this
install.packages("backports")
devtools::install_github("chrisschuerz/SWATplusR")

 Willem

**Comment by chrisschuerz** [comment]
I assume this issue was solved by @WillemVervoort ?
