### ISSUE TITLE
Error in run_swat2012 after update to latest version

### ISSUE THREAD

**Issue by jkurkif** [chrisschuerz/SWATplusR#31]
I have been able to successfully run this model through SWATplusR until I updated it to the latest version of SWATplus R (0.3.4). I now get the following error message. It seems to be running the SWAT successfully, but it is not able to read the output.
Thanks 
  
Q_sim_day <- run_swat2012(project_path = proj_path,
                       output = define_output(file = "rch",variable = "FLOW_OUT",
                                                          unit = 6),output_interval = "d", years_skip = 2)

Completed 1 thread in 25S                                                  
Performing 1 simulation on 1 cores: 
 Simulation 1 of 1   Time elapsed: 37S   Time remaining: 0S    Error in { : 
  task 1 failed - "Result 1 must be a single integer, not an integer vector of length 0"

**Comment by chrisschuerz** [comment]
The code you posted here, worked with my demo setup (except changing the unit, as the demo only has 3 subbasins). I could look into your error, if you can provide me you model setup.

**Comment by jkurkif** [comment]
Must be a problem with my data structure then. Interesting because it runs fine in ArcSWAT. Thanks for checking.

**Comment by jkurkif** [comment]
Just as an update - The problem was that I had ICALEN set to 1 in the CIO file. It needs to be set to 0.

**Comment by chrisschuerz** [comment]
Thanks for the update. Now I remember that someone mailed me about that issue already a year ago. The error message was however different. But good that you remind me. I should set ICALEN to 0 in the running threads that the date format matches my output reading routines.
