### ISSUE TITLE
channel_day.txt does not exist

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#33]
I'm able to run the demo project, but can't get any of my own projects to run. When I call run_swat_plus on my projects I always get the error "[path_to_project]/.model_run/thread_1/channel_day.txt' does not exist."

**Comment by chrisschuerz** [comment]
Which revision number is the model you want to run? The newer revisions (59.3 to 60.5) use the output file channe_sd to write the channel outputs. Please change 'channel' to 'channel_sd' in the output definition and give it a try.

**Comment by seyounger** [comment]
Thanks, that worked. I'm using 60.5
