### ISSUE TITLE
Can't install the development version

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#34]
When I try to install the development version using the instructions in the readme I get the error, "Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/chrisschuerz/SWATplusR/tarball/dev'"

**Comment by chrisschuerz** [comment]
Sorry. The github pages for `SWATplusR` are pretty outdated. I am working on it to update them. Currently there is no development version. All updates are implemented in the `master` branch.

**Comment by chrisschuerz** [comment]
I guess the actual issue is answered (Not that the github page has changed since then 🤔 )
