### ISSUE TITLE
Question regarding  SWAT+ rev. 60.5

### ISSUE THREAD

**Issue by allixender** [chrisschuerz/SWATplusR#35]
Hi,

is it possible to use SWATPLUSR with the latest SWAT+ rev. 60.5 for calibration? Has something changed between SWAT+ rev59.3 and 60.5. We are struggling with SWATPlus-CUP and consider to try SWATPLUSR, but obviously it would be a big challenge to pick up R etc.

Feel free to move the discussion somewhere else.

Best regards,
Alex

**Comment by li3uhua** [comment]
Hi,
When I usd SWATplusR to run SWAT+ model, an error occured (Fig. 1).
I followed an advice to change "channel" to "channel_sd", and the model can run successfully.
I checked my print.prt file, both channel and channel_sd were printed and there were "flow_out" variables in these files (Fig.2).
And I would like to ask how I should select these files?

Fig.1
![Snipaste_2021-06-17_10-55-53](https://user-images.githubusercontent.com/50698220/122717544-505efc00-d29e-11eb-9ef2-40db03aaf010.png)

Fig.2
![Snipaste_2021-06-20_22-05-43](https://user-images.githubusercontent.com/50698220/122717580-5ead1800-d29e-11eb-8187-464e121e049d.png)

**Comment by yulis8** [comment]
> 
> 
> > Dear li3uhua,
> > Do you have the solution of the problems? I have the same error. I tried to copy channel_sd_day.txt to channel_day.txt but the error still occured.
> 
> Hi, try to change the code in R (change the file ="channel" into "channel_sd"). In addition, I still don't know how to choose the files because I haven't found a document mentioning about it. Good luck.

Thanks for the advice...

I will try...
