### ISSUE TITLE
runswat_2012 Error in { :    task 1 failed - "Result 1 must be a single integer, not an integer vector of length 0"

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#36]
I have a swat 2012 project that runs from swat editor. When I try to run from SWATplusR I get the following error. If you can help me figure out what this means I would appreciate it!

```{r}
q_sim_plus <- run_swat2012(project_path = path_2012,
                            start_date = s_date,
                            end_date = e_date,
                            years_skip = 3,
                            output = define_output(file = "rch",
                                                   variable = "FLOW_OUTcms",
                                                   unit = 21))
Building 1 thread in '~/Desktop/Default/TxtInOut/.model_run': 
 Completed 1 thread in 23S                                                  
Performing 1 simulation on 1 cores: 
 Simulation 1 of 1   Time elapsed: 28S   Time remaining: 0S    Error in { : 
  task 1 failed - "Result 1 must be a single integer, not an integer vector of length 0"
```

**Comment by chrisschuerz** [comment]
One reason that I could think of is that the `variable  = "FLOW_OUTcms"` could cause issues. But I actually took care of removing the units. But I would try to use the following `variable  = "FLOW_OUT"` instead, ommiting the unit.

**Comment by seyounger** [comment]
Thanks for your reply. I posted the wrong version. I tried `variable = "FLOW_OUT"` first and got the same error.

**Comment by seyounger** [comment]
This error was due to ICALEN being set to 1 for calendar dates rather than 0 for DOY dates. Looks like run_swat2012 only works with DOY dates.

**Comment by chrisschuerz** [comment]
Hi thanks for posting the solution. This is on my list to implement. It is an easy fix, but I have to find some time to implement it.
