### ISSUE TITLE
Error using absval parameter modification in SWAT2012

### ISSUE THREAD

**Issue by dschaffersmith** [chrisschuerz/SWATplusR#40]
Hi Chris,

I am using the demo project SWAT 2012 and I am getting an error running simulations when I modify 2 parameters, one using pctchg and one using absval. The error I am getting is 

Error in { : 
task 1 failed - "Mapped vectors must have consistent lengths: 
*`.x` has length 33
*`.y` has length 32"

It works fine if I use pctchg for both or pctchg and abschg.

**Comment by chrisschuerz** [comment]
@dschaffersmith could you provide a code example to test it with the demo data set?

**Comment by chrisschuerz** [comment]
@dschaffersmith I just triggered the same error by using the parameter `SURLAG.hru` in a SWAT2012 version where the parameter SURLAG is not present in the `.hru` files and therefore should be defined as `SURLAG.bsn`. Did you maybe use a wrong file extension in the parameter definition of one of your parameters that you wanted to modify?
