### ISSUE TITLE
bug in: vignettes/01_par_sensitivity.Rmd

### ISSUE THREAD

**Issue by AndresSaracho** [chrisschuerz/SWATplusR#43]
bug in: vignettes/01_par_sensitivity.Rmd
https://chrisschuerz.github.io/SWATplusR/articles/01_par_sensitivity.html

does swat_nse is swat_sobol?
within the sensitivity analysis with the method of sobol

sens_sobol <- sobol(model = swat_nse, X1 = x1, X2 = x2, 
                    obs = q_obs$discharge, nboot = 100)

**Comment by chrisschuerz** [comment]
@AndresSaracho You are right this should be `swat_sobol` I will restructure the vignette anyways. I hope this happens soon... 🤔

**Comment by chrisschuerz** [comment]
The github page that showed this issue is currently modified (see also issue #51). Thus, I will close this thread.
