### ISSUE TITLE
Error: 'D:/Projects/model/test/Scenarios/Default/TxtInOut/NA' does not exist.

### ISSUE THREAD

**Issue by mgf-unige** [chrisschuerz/SWATplusR#44]
I try to use run_swatplus with a project and I get "Error: 'D:/Projects/model/test/Scenarios/Default/TxtInOut/NA' does not exist."

q_sim <- run_swatplus(project_path = "D:/Projects/model/test/Scenarios/Default/TxtInOut",
                      output = define_output(file = "channel",
                                             variable = "flo_out",
                                             unit = 1))

I put the swatplus_rev59.exe file in TxtInOut. Any idea why run_swatplus is looking for a NA?

It's maybe related to the other issue https://github.com/chrisschuerz/SWATplusR/issues/42 as I get the same warning about revision: Missing column names filled in: 'X6' [6] 

The model runs well in SWATPlusEditor...

I tried to rebuild the package with the fix from #42 but it doesn't change anything...

**Comment by mgf-unige** [comment]
Alright. There were missing files that weren't created while building the SWAT model. The model runs without problem but apparently, run_swatplus is looking for some other files. I copied the files from the demo (that works) in my model folder and now the function works...

**Comment by chrisschuerz** [comment]
@mgf-unige  Is it OK to close this issue? Unless not please reopen it

**Comment by mgf-unige** [comment]
Yes, it's OK thank you! Great work btw!

**Comment by MOG91** [comment]
> Alright. There were missing files that weren't created while building the SWAT model. The model runs without problem but apparently, run_swatplus is looking for some other files. I copied the files from the demo (that works) in my model folder and now the function works...

I'm having the same issue right now, but I haven't identified the missing files. Do you mind sharing what files did you pasted from the demo folder? 

Thank you!

**Comment by mgf-unige** [comment]
Sorry, but I don't remember them now. I compared the two folders to see what files were missing in my model. You can use it in a prompt:

robocopy C:\ModelExampleFolder C:\YourModelFolder /MIR /FP /NDL /NP /L > diff.txt

Then, open the diff.txt file and look for files tagged "New file". There are the files in the example model that are missing in your model (maybe not all of them but I copied all of them while testing). Btw, I have recreated my model since then and haven't needed to do that again so I don't know what caused those missing files...
