### ISSUE TITLE
SWAT+ don't generate the .PCP files required in SWATplusR

### ISSUE THREAD

**Issue by MOG91** [chrisschuerz/SWATplusR#50]
This issue is closely related to #45, when I try to run my own model with run_swatplus, I get the same error:

```
> #SWAT+ MODEL PATH
> path <- "C:/SWATplus-proj/Tomb/model/Scenarios/Default/TxtInOut"
> setwd(path)
> 
> #Define desired model outputs
> 
> 
> 
> #Run simulation
> q_out <- run_swatplus(project_path = path, 
+                       output = define_output(file = "channel_sd_mon",
+                                              variable = "flo_out",
+                                              unit = c(17)),
+                       n_thread = 4,
+                       save_file = "run_test",
+                       output_interval = "m")
Error: 'C:/SWATplus-proj/Tomb/model/Scenarios/Default/TxtInOut/NA' does not exist.
```

And this does not happen with the demo project. When I paste the .PCP files from the demo to my model, it does run, so the NA is generated when run_SWATplus searches for these .PCP files.

**Comment by MOG91** [comment]
Thanks for your reply Chris! Yes, I'm currently using only simulated data. Is there a way to use SWATplusR with such model or what would be a quick workaround for this issue? Adding a single precipitation station would allow the run_SWATplus function to run? Do you have any suggestions? Again, thank you so much and thank you for developing this tool.

**Comment by chrisschuerz** [comment]
I will change this in the code (but I guess not before next week) that you can also run the model without weather data and only get a warning that there are no input data for the period you want to run simulations. 
In the meantime you can use the [dummy.pcp.txt](https://github.com/chrisschuerz/SWATplusR/files/7941732/dummy.pcp.txt) file that I added here to fool the R code ☺️ You have to replace the file ending '.txt' and add it into your project folder. I did not have time to test it, but it should do the trick. Please let me know if it worked or not.

**Comment by MOG91** [comment]
Yes, it works! Thank you very much for your help.
