### ISSUE TITLE
run_swat2012 can't find linux executable for user project

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#53]
On linux the function run_swat2012 works fine for the demo project but fails for a user-created project. It says it cannot find the executable even though it is in the project folder. Any advice is appreciated.

```{r}
Error in build_model_run(project_path, run_path, n_thread, os, swat_vers,  : 
  No SWAT executable found in the project folder!
```

**Comment by chrisschuerz** [comment]
@seyounger On Linux it is a bit harder to identify which file the actual executable is, or at least it is for me and might not apply to more experienced programmers. Could you check the file properties of the executable that you copied to your project. In the properties where you define read write access etc. you should also be able to define the file to be executable. Maybe this does the trick.

**Comment by seyounger** [comment]
@chrisschuerz Ah, thanks. I had to do: chmod +x swat2012_rev637

However, now I keep getting an error about "model_setup" after the run with no outputs printed.

```{r}
q_sim_2012_demo <- run_swat2012(project_path = "demo/swat2012_rev637_demo",
                           output = define_output(file = "rch",
                                                  variable = "FLOW_OUT",
                                                  unit = 1))

Completed 1 thread in 0S                                                   
Performing 1 simulation on 1 cores: 
 Completed 1 simulation in 3S                                               
Error in stri_sub(string, from = start, to = end) :
argument "model_setup" is missing, with no default
```

Is there something different about defining outputs for unix? I looked through the docs but didn't find anything. Thanks!
