### ISSUE TITLE
problem with version 0.5.2 - argument "model_setup" is missing, with no default

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#55]
I thought this was specific to linux but it turns out I get the same error on windows. Seems to be related to recent changes in 0.5.2

```{r}
q_sim_2012_demo <- run_swat2012(project_path = "demo/swat2012_rev637_demo",
                           output = define_output(file = "rch",
                                                  variable = "FLOW_OUT",
                                                  unit = 1))

Completed 1 thread in 0S                                                   
Performing 1 simulation on 1 cores: 
 Completed 1 simulation in 3S                                               
Error in stri_sub(string, from = start, to = end) :
argument "model_setup" is missing, with no default
```

**Comment by seyounger** [comment]
If anyone else runs into this I was able to install the previous release, which works.

```devtools::install_github("chrisschuerz/SWATplusR@200708a2627fed0754f2ec9f82f3d2e1af16ea38", force = TRUE)```

**Comment by chrisschuerz** [comment]
@seyounger Thanks for the info. I might have messed up something when I updated some other things in `SWATplusR`. I will look into that. In the meantime it might be the best workaround to use an older version as you suggested.

**Comment by chrisschuerz** [comment]
@seyounger I just fixed the issue. The changes in the update to rev 0.5.2 did not consider SWAT2012. I updated `SWATplusR` now to version 0.5.3. This version should also work with SWAT2012 again.

**Comment by seyounger** [comment]
Thanks, @chrisschuerz. version 0.5.3 does work
