### ISSUE TITLE
SWAT2012 PLANT_ID parameter is truncated with varying .mgt input formats

### ISSUE THREAD

**Issue by seyounger** [chrisschuerz/SWATplusR#57]
Some SWAT2012 model creation tools like [HAWQS](https://hawqs.tamu.edu/#/) produce .mgt files with different spacing than ArcSWAT. For files with this different spacing some PLANT_ID's get modified when the parameters are modified, but not if parameters are left alone. Two digit PLANT_ID's get truncated to only their first digit. 10 and 15 both become 1. I wonder if there is a simple way to address this?

[Here is one of the offending .mgt files](https://www.dropbox.com/s/xgyui8go0h4hor9/000760116.mgt?dl=0) 

This input
```{r input}
.mgt file Watershed HRU:4538 Subbasin:76 HRU:116 Luse:RNGE Soil:GA052 Slope:0-1 9/9/2021 8:57:55 AM EPA-HAWQS v1.2 (030602020107)
0                   | NMGT:Management code
Initial Plant Growth Parameters
1                   | IGRO: Land cover status: 0-none growing; 1-growing
15                  | PLANT_ID: Land cover ID number (IGRO = 1)
2.00                | LAI_INIT: Initial leaf are index (IGRO = 1)
1000.00             | BIO_INIT: Initial biomass (kg/ha) (IGRO = 1)
2500.00             | PHU_PLT: Number of heat units to bring plant to maturity (IGRO = 1)

```

Gets converted to this output after a thread is created and ran
```{r outut}
.mgt file Watershed HRU:4538 Subbasin:76 HRU:116 Luse:RNGE Soil:GA052 Slope:0-1 9/9/2021 8:57:55 AM EPA-HAWQS v1.2 (030602020107)
0                   | NMGT:Management code
Initial Plant Growth Parameters
1                   | IGRO: Land cover status: 0-none growing; 1-growing
1                   | PLANT_ID: Land cover ID number (IGRO = 1)
   2                | LAI_INIT: Initial leaf are index (IGRO = 1)
   1000             | BIO_INIT: Initial biomass (kg/ha) (IGRO = 1)
   2500             | PHU_PLT: Number of heat units to bring plant to maturity (IGRO = 1)
```

**Comment by chrisschuerz** [comment]
OK interesting I will have a look into that. It should actually take all of the first 16 digits of a line and generate a numeric from it.

**Comment by chrisschuerz** [comment]
@seyounger I just tested it with a small example. I did not receive any .mgt files as you did and PLANT_ID remains to be a 3 digit number. Also the formatting of the values is different in my case, as `run_swat2012` writes tabular parameter values always as 16 digit float numbers with leading blanks, which is not the case in the example you provided. I am sorry I cannot reproduce what you got.

**Comment by seyounger** [comment]
Thanks for looking, @chrisschuerz ! I will close this since it seems to be a HAWQS issue. I should have included an example. In case you have a chance to take another look [here is a scenario with an offending file](https://www.dropbox.com/s/sjt41ute814nsli/HAWQS_mgt.zip?dl=0). One of the problem files is 000760116.mgt
