### ISSUE TITLE
Error when add_date=T

### ISSUE THREAD

**Issue by Yang2Rechard** [chrisschuerz/SWATplusR#58]
Error in `bind_cols()`:
! Can't recycle `..1` (size 12168) to match `..2` (size 312).
this error occured when excute run_swatplus with rev60.5.3,the project contains 39 channels, and ran at monthly interval for 26 years, when the add_date = F, everything is alright, while ad_date = T, which is the default case, the above error occured, I think there is a bug in the function to get date, or is there something wrong in my project setup? please anyboy help!!
![image](https://user-images.githubusercontent.com/34668955/158101049-cd52f22e-ba8e-4cd4-a0ff-31c181bdc527.png)

**Comment by Yang2Rechard** [comment]
this error occured when excute run_swatplus

**Comment by chrisschuerz** [comment]
@Yang2Rechard Yes I apparently introduced this issue when I implemented a different way to read dates for SWAT+ model runs. I fixed this issue now. The updated version `SWATplusR 0.5.5` should work again.
