### ISSUE TITLE
Issue installing SWATplusR from github repository

### ISSUE THREAD

**Issue by jsacerot** [chrisschuerz/SWATplusR#7]
I'm facing the problem below. Could you please guide me on how to fix it? I'll appreciate it. Thanks!

> devtools::install_github("chrisschuerz/SWATplusR")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’

> devtools::install_github("chrisschuerz/SWATplusR", ref = "dev")
Error: .onLoad failed in loadNamespace() for 'pkgload', details:
  call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
  error: there is no package called ‘backports’

**Comment by chrisschuerz** [comment]
Hi,

according to your error message, you do not have the package ``backports`` installed. ``SWATplusR`` does not require that, but it seems as ``devtools`` would require that. So try:

```r
install.packages("backports")
```

Hope that does the trick. If you see any similar errors with other packages try the same.

Cheers Christoph
