### ISSUE TITLE
HRU output SWAT2012

### ISSUE THREAD

**Issue by rafaelnavas** [chrisschuerz/SWATplusR#8]
I have problems to obtain HRU outputs with "run_swat2012". I`m using the next command line:

q_sim <- run_swat2012(project_path = swat_dir,
                      start_date = "2009-01-01",
                      end_date = "2010-12-31",
                      years_skip = 1,
                      output = define_output(file="hru",
                                             variable = "ETmm",
                                             unit = 1)
                      )

Then, I obtain the next message:

Building 1 thread in 'C:/SWAT_SL_level5/SWATCUP-files//.model_run': 
 Completed 1 thread in 23S                                                  
Performing 1 simulation on 1 cores: 
 Simulation 1 of 1   Time elapsed: 21S   Time remaining: 0S    Error in { : 
  task 1 failed - "`nm` must be `NULL` or a character vector the same length as `x`"

**Comment by chrisschuerz** [comment]
Hi thanks for posting the issue. I will try to have a look into that by mid of this week.

**Comment by chrisschuerz** [comment]
Hi Rafael,

I finally found time today, to look into your issue. Indeed there were some problems with reading the HRU output table, particularly with the most recent Revision of SWAT2012. I fixed and tested the issue with a minimum example. It should work now. So please just reinstall `SWATplusR` it should be Version 2.8.9003 now and test it. Just let me know if you run into the same or other troubles now.

Cheers, Christoph

**Comment by rafaelnavas** [comment]
Hi Cristoph,
The problem seems to be solved.
Note that Library"stringr" need to be added to allow the use of function "str_remove" in the new Version 0.2.8.9003.
Thank you

**Comment by chrisschuerz** [comment]
Hi Rafael,

thanks I guess I forgot to add the function `str_remove` to the functions that are loaded with the output read function call. I will fix that in the the next version 0.2.8.9004 but anyways good that the HRU reading now works!

**Comment by rafaelnavas** [comment]
Dear Chris,
I installed SWATplusR again with:
option1: install_github("chrisschuerz/SWATplusR")
option2: install_github("chrisschuerz/SWATplusR", ref = "dev").

In both cases, I getting version 0.2.7 with the bug reported in this issue #8.

However, when I install your package with:
install_github("willemvervoort/SWATplusR", ref="RevisionMod")
the problem is solved since version 0.2.8.9006 is installed.

Rafael

**Comment by chrisschuerz** [comment]
Hi,

this is odd. The current version of SWATplusR is 0.3.2. Which version of R do you use. The most recent version requires you to have R > R4.0 installed. This could maybe be the reason why `install_github()` tries to install the older version.

Chris

**Comment by rafaelnavas** [comment]
This is weird,
I'm currently using version R version 4.0.2 (2020-06-22).
Maybe the problems is devtools or windows OS.
Let me check.
Thank you
